import { SiteHeader } from "@/components/site-header";
import { CThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { ThirdwebProvider } from "thirdweb/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative flex min-h-dvh flex-col bg-background">
      <CThemeProvider disableTransitionOnChange defaultTheme="dark-soft">
        <ThirdwebProvider>
          <SiteHeader/>
          {children}
          </ThirdwebProvider></CThemeProvider>
          </div>
  );
}